name: Build Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install 3rdp dependencies
      run: ./scripts/update-3rdp.bat
    - name: Generate build files
      run: ./scripts/build-projects-vs2022-win64.bat
    - name: Build DebugShared
      run: ./scripts/autobuild/autobuild-latest-win64.bat DebugShared
    - name: Build ReleaseShared
      run: ./scripts/autobuild/autobuild-latest-win64.bat ReleaseShared
    - name: Build ReleaseStatic
      run: ./scripts/autobuild/autobuild-latest-win64.bat ReleaseStatic
    - name: Unit tests DebugShared
      run: ./bin/latest/win64/debugshared/Traktor.Run.App ./scripts/unittest/UnitTest.run
    - name: Unit tests ReleaseShared
      run: ./bin/latest/win64/releaseshared/Traktor.Run.App ./scripts/unittest/UnitTest.run
    - name: Create Installer
      run: ./scripts/autobuild/autobuild-installer-win64.bat
    - name: Archive Installer
      uses: actions/upload-artifact@v4
      with:
        name: Installer
        path: build/installer/Traktor.msi
