name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install APT dependencies
      run: sudo ./scripts/misc/install-linux-deps.sh
    - name: Install 3rdp dependencies
      run: sudo ./bin/linux/releasestatic/Traktor.Run.App ./scripts/misc/update-3rdp.run
    - name: Generate build files
      run: ./scripts/build-projects-make-linux.sh
    - name: Build DebugShared
      run: ./scripts/autobuild/autobuild-latest-linux.sh DebugShared
    - name: Build ReleaseShared
      run: ./scripts/autobuild/autobuild-latest-linux.sh ReleaseShared
